# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import arithmetic_pb2 as arithmetic__pb2


class ArithmeticStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/arithmetic.Arithmetic/Add',
                request_serializer=arithmetic__pb2.ArithmeticRequest.SerializeToString,
                response_deserializer=arithmetic__pb2.Result.FromString,
                )
        self.Subtract = channel.unary_unary(
                '/arithmetic.Arithmetic/Subtract',
                request_serializer=arithmetic__pb2.ArithmeticRequest.SerializeToString,
                response_deserializer=arithmetic__pb2.Result.FromString,
                )
        self.Multiply = channel.unary_unary(
                '/arithmetic.Arithmetic/Multiply',
                request_serializer=arithmetic__pb2.ArithmeticRequest.SerializeToString,
                response_deserializer=arithmetic__pb2.Result.FromString,
                )
        self.Divide = channel.unary_unary(
                '/arithmetic.Arithmetic/Divide',
                request_serializer=arithmetic__pb2.ArithmeticRequest.SerializeToString,
                response_deserializer=arithmetic__pb2.Result.FromString,
                )


class ArithmeticServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArithmeticServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=arithmetic__pb2.ArithmeticRequest.FromString,
                    response_serializer=arithmetic__pb2.Result.SerializeToString,
            ),
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=arithmetic__pb2.ArithmeticRequest.FromString,
                    response_serializer=arithmetic__pb2.Result.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=arithmetic__pb2.ArithmeticRequest.FromString,
                    response_serializer=arithmetic__pb2.Result.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=arithmetic__pb2.ArithmeticRequest.FromString,
                    response_serializer=arithmetic__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arithmetic.Arithmetic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Arithmetic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arithmetic.Arithmetic/Add',
            arithmetic__pb2.ArithmeticRequest.SerializeToString,
            arithmetic__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arithmetic.Arithmetic/Subtract',
            arithmetic__pb2.ArithmeticRequest.SerializeToString,
            arithmetic__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arithmetic.Arithmetic/Multiply',
            arithmetic__pb2.ArithmeticRequest.SerializeToString,
            arithmetic__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arithmetic.Arithmetic/Divide',
            arithmetic__pb2.ArithmeticRequest.SerializeToString,
            arithmetic__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
