# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arithmetic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61rithmetic.proto\x12\narithmetic\"/\n\x11\x41rithmeticRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\x81\x02\n\nArithmetic\x12\x38\n\x03\x41\x64\x64\x12\x1d.arithmetic.ArithmeticRequest\x1a\x12.arithmetic.Result\x12=\n\x08Subtract\x12\x1d.arithmetic.ArithmeticRequest\x1a\x12.arithmetic.Result\x12=\n\x08Multiply\x12\x1d.arithmetic.ArithmeticRequest\x1a\x12.arithmetic.Result\x12;\n\x06\x44ivide\x12\x1d.arithmetic.ArithmeticRequest\x1a\x12.arithmetic.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arithmetic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARITHMETICREQUEST']._serialized_start=32
  _globals['_ARITHMETICREQUEST']._serialized_end=79
  _globals['_RESULT']._serialized_start=81
  _globals['_RESULT']._serialized_end=105
  _globals['_ARITHMETIC']._serialized_start=108
  _globals['_ARITHMETIC']._serialized_end=365
# @@protoc_insertion_point(module_scope)
